### ISSUE TITLE
Dynamic Import and Long Term Caching

### ISSUE THREAD

**Issue by dNitro** [SassNinja/media-query-plugin#21]
In part 3 of README you've described how to use extracted files through dynamic import but what if the name of extracted files includes a hash ( i.e. `[name].[contenthash].css` generated through MiniCssExtractPlugin then Splitted using MediaQueryPlugin ) ? Is it possible to dynamic import generated files that have a hash in them via this plugin?

**Comment by SassNinja** [comment]
Hi @dNitro 

> Is it possible to dynamic import generated files that have a hash in them via this plugin?

Yes, that's why you've to create an empty SCSS file that get's populated with the extracted CSS.
Since your dynamic import is part of the bundle it knows the hash.

Check the example folder to see how to use it
https://github.com/SassNinja/media-query-plugin/tree/master/examples/webpack
