### ISSUE TITLE
how to remove warning

### ISSUE THREAD

**Issue by Capricair** [SassNinja/media-query-plugin#85]
[WARNING] media-query-plugin is going to drop webpack 4 support with the next major version so you should consider upgrading asap!

**Comment by SassNinja** [comment]
Hi @Capricair 

you're seeing this warning because you're not using the latest webpack version.
It's a friendly reminder to upgrade so that you won't be affected by a breaking change in future.

So the simple answer to your question "how to remove warning" is: upgrade your webpack 😉 
Is there anything blocking you? Sooner or later you'll probably get problems with other loaders/plugins as well.

**Comment by Capricair** [comment]
> Hi @Capricair
> 
> you're seeing this warning because you're not using the latest webpack version. It's a friendly reminder to upgrade so that you won't be affected by a breaking change in future.
> 
> So the simple answer to your question "how to remove warning" is: upgrade your webpack 😉 Is there anything blocking you? Sooner or later you'll probably get problems with other loaders/plugins as well.

Sorry, my project use nuxt 2, cannot upgrade to webpack5 at this time, can you give a option to disable it?
